#INITIAL SETTINGS
url: 'https://www.dropbox.com/'
train_ratio: 0.7
test_ratio: 0.15
validate_ratio: 0.15
randomstate : 42
drop_fields: ["PetID","Name","Age","Breed1","Breed2","VideoAmt","PhotoAmt","Fee","State",
              "RescuerID","Description","TypeName","GenderName","MaturitySizeName",
              "FurLengthName","HealthName","DewormedName","Color1","Color2","Color3",
              "VaccinatedName","BreedName","StateName","Quantity","AdoptedName",
              "StateBinsName","SterilizedName"]

#DECISISONTREE
max_depth_dt: [3, 5, 7, 10]
#RANDOMFOREST
max_depth_rf: [3, 5, 7, 10]
n_estimators_rf: [50, 100, 150, 200]
#GRADIENTBOOSTING
max_depth_gb: [3, 5, 7, 10]
n_estimators_gb: [50, 100, 150, 200]
learning_rate_gb: [0.1, 0.01, 0.001]
#SVM
c_svm: [0.1, 1]
gamma_svm: [0.1, 1]
kernel_svm: ['rbf']
#LOGISTICREGRESSION
c_lr: [0.1, 1, 10]
penalty_lr: ['l1', 'l2', 'elasticnet', 'none']
solver_lr: ['saga']
# NEURAL NETWORK CONFIG
hidden_layer_sizes_nn: [(50,), (100,)]
activation_nn: ['relu', 'tanh']
solver_nn: ['adam']
learning_rate_schedule_nn: ['constant']
# XGBOOST
learning_rate_xgboost: [0.1]
max_depth_xgboost: [10]
n_estimators_xgboost: [100]
# LIGHTGBM
learning_rate_lightgbm: [0.1]
max_depth_lightgbm: [10]
n_estimators_lightgbm: [100]
# CATBOOST
learning_rate_catboost: [0.1]
max_depth_catboost: [10]







